"""Add city and hh_area_id to users

Revision ID: bfd9fddf3db7
Revises: 17ed2c8c1088
Create Date: 2025-11-25 01:44:46.140196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd9fddf3db7'
down_revision = '17ed2c8c1088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('hh_area_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hh_area_id')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###